
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
  backend:
    build: ./services/backend-rust
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo
